scripts/gcs_upload.py
This PR adds an option to perform GCS uploads using `gcloud alpha storage cp`, a new, faster alternative to `gsutil cp`.
For details, see https://cloud.google.com/blog/products/storage-data-transfer/new-gcloud-storage-enables-super-fast-data-transfers.
**Important**: gcloud alpha components must be installed before using this option.
To do so, run `gcloud components install alpha` from a terminal
The API is equivalent to `gsutil cp`, so I refactored the `gsutil` methods to accept either command.
Running distributed could be accomplished either by passing files via stdin (`-I`), in which case original directory structure is lost, or by running multiple instances on different subdirectories. Currently, only running on a single machine is supported. It will use all available threads.
Tested …
=> Feat: gcloud alpha storage

scripts/bin/compress_open_ephys_job.sh, src/transfer/configuration_loader.py, src/transfer/jobs/open_ephys_job.py, src/transfer/writers.py, tests/test_compressors.py, tests/test_configuration_loader.py
=> Fix 22 blosc enums

src/transfer/compressors.py, src/transfer/readers.py, src/transfer/writers.py, tests/test_readers.py
=> Use experiment name instead of block index in zarr output folders

pyproject.toml
=> Fix 42: upgrade wavpack-numcodecs to 0.1.2

src/transfer/__init__.py, src/transfer/configuration_loader.py, src/transfer/jobs/openephys_job.py, src/transfer/readers.py
Closes #48
Small refactoring and fix for gcp upload command
=> tech-debt: refactors enum and fixes gcp upload command

src/transfer/__init__.py, src/transfer/writers.py
Quickly adds an option in case the video folder is labeled "videos" instead of "Videos"
=> hot-fix: quick for video directory bug

src/transfer/__init__.py, src/transfer/util/npopto_correction.py
Closes #59 
And pre-calculates correct NP-opto locations
=> fix: np-opto correction

conf/ephys_upload_job_configs.yml, src/aind_data_transfer/__init__.py, src/aind_data_transfer/configuration_loader.py, src/aind_data_transfer/jobs/openephys_job.py, src/aind_data_transfer/transformations/metadata_creation.py, src/aind_data_transfer/util/npopto_correction.py, tests/resources/test_configs/ephys_upload_job_test_configs.yml, tests/resources/test_configs/example_configs_src_pattern1.yml, tests/resources/test_configs/example_configs_src_pattern2.yml, tests/resources/test_metadata/processing.json, tests/test_configuration_loader.py
Closes #39 
Adds basic logging to ephys job pipeline.
=> feat: adds logging to ephy job

conf/ephys_upload_job_configs.yml, src/aind_data_transfer/__init__.py, src/aind_data_transfer/codeocean.py, src/aind_data_transfer/configuration_loader.py, src/aind_data_transfer/jobs/openephys_job.py, tests/resources/test_configs/ephys_upload_job_test_configs.yml, tests/resources/test_configs/example_configs_src_pattern1.yml, tests/resources/test_configs/example_configs_src_pattern2.yml, tests/resources/test_metadata/processing.json, tests/test_codeocean_requests.py, tests/test_configuration_loader.py
Closes #51
Hopefully, this will suffice for now. I imagine it might be better to create a CodeOcean capsule to handle a few of the processes.
=> Feat 51 ephys capsule trigger

pyproject.toml
=> fix: update probeinterface version

.github/workflows/tag_and_publish.yml, src/aind_data_transfer/__init__.py, tests/resources/test_metadata/processing.json
updated pypi publish action to v1.5
=> fix: use version 1.5 of pypi publish action

conf/ephys_upload_job_configs.yml, src/aind_data_transfer/__init__.py, src/aind_data_transfer/config_loader/ephys_configuration_loader.py, src/aind_data_transfer/jobs/openephys_job.py, src/aind_data_transfer/util/s3_utils.py, src/aind_data_transfer/writers.py, tests/resources/test_configs/ephys_upload_job_test_configs.yml, tests/resources/test_configs/example_configs_src_pattern1.yml, tests/resources/test_configs/example_configs_src_pattern2.yml, tests/resources/test_metadata/processing.json, tests/test_configuration_loader.py
Closes #106
- Adds an option for a user to select a videos directory that exists outside the path of the raw data source.
=> feat: adds option for alt vid dir

scripts/openephys_job.py, src/aind_data_transfer/__init__.py, src/aind_data_transfer/jobs/openephys_job.py
Closes #116 
- Adds template python script to run job
=> Feat 116 bash to py

src/aind_data_transfer/__init__.py, src/aind_data_transfer/jobs/transcode_job.py
Makes parsing of the optional transcode job arguments more robust
=> fix transcode job argument parsing

.github/workflows/ci.yml, .github/workflows/tag_and_publish.yml, tests/resources/test_metadata/processing.json
This should finally resolve the automatic version bump and publishing to pypi
=> feat: automates version bump

src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_metadata/data_description.json, tests/test_metadata_creation.py
=> Feat 108 add datadescription

src/aind_data_transfer/jobs/s3_upload_job.py, tests/test_generic_upload_job.py
- Adds bucket and prefix to code ocean trigger capsule job parameters
=> fix: fixes generic job capsule params

conf/smartspim_upload_job_configs.yml, scripts/gcs_upload.py, scripts/s3_upload.py, scripts/smartspim_job.py, scripts/write_ome_zarr.py, src/aind_data_transfer/__init__.py, src/aind_data_transfer/config_loader/configuration_loader.py, src/aind_data_transfer/gcs.py, src/aind_data_transfer/jobs/smartspim_job.py, src/aind_data_transfer/readers.py, src/aind_data_transfer/s3.py, src/aind_data_transfer/transcode/ome_zarr.py, src/aind_data_transfer/util/chunk_utils.py, src/aind_data_transfer/util/file_utils.py, src/aind_data_transfer/util/io_utils.py, src/aind_data_transfer/util/npopto_correction.py, src/aind_data_transfer/writers.py, tests/test_chunk_utils.py, tests/test_gcs_uploader.py, tests/test_io_utils.py, tests/test_ome_zarr.py, tests/test_readers.py
Feature to upload smartspim datasets to S3 and trigger the stitching capsule.
=> Feat smartspim

README.md, src/aind_data_transfer/jobs/s3_upload_job.py, tests/resources/test_configs/jobs_list.csv, tests/test_generic_upload_job.py
Closes #136 
- Adds some documentation on Generic Upload Job usage
- Adds script to loop through job params defined in a csv file
=> Feat 136 generic loop

src/aind_data_transfer/jobs/openephys_job.py
=> Fix: correct np-opto locations before clipping

src/aind_data_transfer/config_loader/ephys_configuration_loader.py
=> patch: fixes small bug with key name

scripts/s3_upload.py, scripts/smartspim_job.py, src/aind_data_transfer/readers/imaging_readers.py, src/aind_data_transfer/util/file_utils.py
Modifying regular expression to accept smartspim ids coming from NYU and CU. Additionally, I changed the configuration for the HPC cluster since I got a better performance.
=> updating scripts to accept smartspims idsd from NYU and CU

src/aind_data_transfer/jobs/s3_upload_job.py, tests/test_generic_upload_job.py
=> Feat 165 extra datetime

conf/smartspim_upload_job_configs.yml, scripts/s3_upload.py, scripts/smartspim_job.py, src/aind_data_transfer/writers/imaging_writers.py
Fixes #163, #164 and #171. Additionally, I patched the bug when we're not able to find files in a given directory and the HPC jobs kept going.
=> Feat smartspim pipeline params

pyproject.toml, scripts/s3_upload.py, scripts/smartspim_job.py, scripts/validate_datasets.py, src/aind_data_transfer/util/file_utils.py, src/aind_data_transfer/writers/imaging_writers.py
Validation script for SmartSPIM datasets. If there are more validations that need to be performed, we could create a package only for data validation coming from the microscopes.
=> adding smartspim validation script

pyproject.toml, src/aind_data_transfer/config_loader/ephys_configuration_loader.py, src/aind_data_transfer/jobs/openephys_job.py, src/aind_data_transfer/jobs/s3_upload_job.py, src/aind_data_transfer/readers/ephys_readers.py, src/aind_data_transfer/transformations/metadata_creation.py, tests/test_ephys_config_loader.py, tests/test_generic_upload_job.py, tests/test_metadata_creation.py
Closes #109 
Closes #178
- Refactors MetadataCreation classes
- Adds Procedures metadata creation class
- Updates the ephys job and generic upload job to attach procedures to outgoing data assets
- In a different ticket, I'll refactor the code base to have the generic job also runt the ephys stuff
=> Feat 109, 178 create procedures

src/aind_data_transfer/jobs/transcode_job.py, src/aind_data_transfer/transcode/ome_zarr.py, tests/test_ome_zarr.py
=> feat: add .zarr extension to images

src/aind_data_transfer/jobs/s3_upload_job.py, src/aind_data_transfer/transformations/generic_compressors.py, src/aind_data_transfer/transformations/metadata_creation.py, src/aind_data_transfer/writers/ephys_writers.py, tests/test_compressors.py, tests/test_generic_upload_job.py
=> Feat 183 optional zip compression

README.md, pyproject.toml, src/aind_data_transfer/config_loader/base_config.py, src/aind_data_transfer/config_loader/ecephys_config.py, src/aind_data_transfer/config_loader/ephys_configuration_loader.py, src/aind_data_transfer/jobs/basic_job.py, src/aind_data_transfer/jobs/ecephys_job.py, src/aind_data_transfer/jobs/openephys_job.py, src/aind_data_transfer/jobs/s3_upload_job.py, src/aind_data_transfer/readers/ephys_readers.py, src/aind_data_transfer/transformations/ephys_compressors.py, src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_configs/jobs_list2.csv, tests/test_basic_job.py, tests/test_compressors.py, tests/test_ecephys_configs.py, tests/test_ecephys_job.py, tests/test_ephys_readers.py, tests/test_generic_upload_job.py, tests/test_metadata_creation.py
Closes #180
- Refactors Ephys upload job
- Flags old modules as deprecated
- Uses pydantic to define configs
- Uses same interface as basic job
=> Feat 180 ecephys update

src/aind_data_transfer/transformations/converters.py, src/aind_data_transfer/transformations/file_io.py
Added converter code as presented in light sheet meeting. 
Feature is not finalized. Needs: 
- Aind-data-schema installation in config files
- Minor modifications to direction attribute
- Full round of testing on actual exaspim and dispim dataset.
=> Initial commit, file_io.py and converters.py

README.md, pyproject.toml, src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_metadata/data_description.json
Closes #214 
- Upgrades to latest aind-data-schema version
- Updates unit tests
- Defaults to empty list for now
=> feat: upgrades aind-data-schema

src/aind_data_transfer/config_loader/base_config.py
Closes #218 
- Converts relative paths to absolute paths
=> fix: sanitizes paths

src/aind_data_transfer/jobs/basic_job.py, src/aind_data_transfer/util/s3_utils.py, tests/test_basic_job.py
Hot fix to close #231 
- Runs sync command on empty directory to test that user has aws cli installed and has correct write privileges
=> Feat 231 aws check

scripts/singularity/aind_data_transfer.def, src/aind_data_transfer/config_loader/base_config.py, tests/test_generic_upload_job.py
- Quick fix to add awscli to the singularity container
- Quick fix with config resolution
=> Hot fix aws cli singularity

src/aind_data_transfer/jobs/transcode_job.py, src/aind_data_transfer/transformations/converters.py
Missed a function parameter on the last commit, trivial fix included in this PR.
=> Update transcode_job.py to run with log_dict

src/aind_data_transfer/transformations/converters.py
this was recently updated to List[str] in aind-data-schema
=> fix experimenter_full_name type in acquisition.json

README.md, pyproject.toml, tests/resources/test_metadata/data_description.json, tests/resources/test_metadata/procedures.json, tests/resources/test_metadata/processing.json, tests/resources/test_metadata/subject.json, tests/test_metadata_creation.py
Closes #277 
- Updates aind-data-schema
- Updates unit tests
=> feat: updates aind-data-schema

scripts/write_ome_zarr.py, src/aind_data_transfer/__init__.py, src/aind_data_transfer/transformations/flatfield_correction.py, src/aind_data_transfer/transformations/ome_zarr.py, src/aind_data_transfer/util/dask_utils.py, src/aind_data_transfer/util/setup_logging.py
=> Feat: add hostname to logging 

src/aind_data_transfer/config_loader/base_config.py, tests/test_base_config.py
fixes issue with parsing datetime strings
=> fix: updates datetime regex pattern

src/aind_data_transfer/jobs/basic_job.py, src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_metadata/metadata.json, tests/test_basic_job.py, tests/test_metadata_creation.py
=> metadata record

pyproject.toml
=> Upgrade spikeinterface and probeinterface

src/aind_data_transfer/config_loader/base_config.py, src/aind_data_transfer/jobs/basic_job.py
Fixes issue with process_name not being set. We need to import the JobConfig from aind-data-transfer-service in the future
=> fix: process name config

pyproject.toml
Hot fix to update the version of probeinterface
=> fix: updates probeinterface

src/aind_data_transfer/transformations/ome_zarr.py
=> Fix OME-Zarr voxel size metadata

src/aind_data_transfer/jobs/basic_job.py
- Adds a log line to check which bucket the data is being uploaded to
- Ran linter on the file
=> docs: add logs

pyproject.toml
Bug fixes for https://github.com/AllenNeuralDynamics/aind-ephys-pipeline-kilosort25/issues/10
=> Upgrade spikeinterface to 0.100.5

src/aind_data_transfer/config_loader/base_config.py, src/aind_data_transfer/jobs/basic_job.py, src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_configs/jobs_list.csv, tests/resources/test_configs/jobs_list2.csv, tests/resources/test_configs/jobs_list3.csv, tests/resources/test_configs/jobs_list4.csv, tests/resources/test_metadata/data_description.json, tests/test_base_config.py, tests/test_basic_job.py, tests/test_generic_upload_job.py, tests/test_metadata_creation.py, tests/test_zarr_upload_job.py
Closes #312 
- Updates data description creation to pull funding info from smartsheet
- Allows user to define code ocean process capsule id using same field name as aind-data-transfer-service
=> feat: updates data description creation

src/aind_data_transfer/transformations/metadata_creation.py, tests/resources/test_metadata/data_description.json, tests/resources/test_metadata/metadata.json
- Adds project name to data description file
=> hot-fix: data description project name

src/aind_data_transfer/config_loader/base_config.py, tests/test_base_config.py
- Adds "AIND Scientific Computing" as default processor_full_name for jobs that run using aind-data-transfer
=> feat: updates processor_name

README.md
Closes #343 
- Adds deprecation warning in README file
=> docs: deprecation warning
