AllenNeuralDynamics/aind-data-transfer

- scripts/s3_upload.py
Currently, if uploading a directory to s3 using the `--cluster` flag, all files are stored as a flat list under ```--s3_path```, which is not the intended behavior. This PR fixes this so the original directory structure is kept.
> fix(s3-upload): s3 dir structure lost when using --cluster

- src/transfer/gcs.py
- src/transfer/s3.py
- tests/test_gcs_uploader.py
- tests/test_s3_transfer.py
fixed an `ModuleNotFoundError: No module named 'util'` error with a fresh conda environment, though I'm no longer able to reproduce it.
> fix(s3-upload): use relative import for util package

- conf/ephys_upload_job_configs.yml
- src/transfer/compressors.py
- src/transfer/writers.py
- tests/resources/ephys_upload_job_test_configs.yml
- tests/test_configuration_loader.py
Closes #36 
- Somplifies the chunk retrieval operation
- Sets default `n_jobs` to `-1` to use all available CPUs (using `os.cpu_count()`)
**NOTE**: the compression bug was triggered by a channel in the LFP stream having all constant values
> Fix 36: ephys compression bug

- .github/workflows/ci.yml
- pyproject.toml
- src/transfer/__init__.py
Closes #65
Slightly different than the behavior in the ticket. 
`pip install .[ephys]`
`pip install .[imaging]`
`pip install .[full]` for both ephys and imaging
`pip install .` just installs the packages in the dependencies list (the stuff shared by ephys and imaging)
> feat: Splits ephys and imaging dependencies

- .github/workflows/tag.yml
- src/aind_data_transfer/__init__.py
I'm going to comment this out to avoid github errors showing up in emails. We can uncomment once we get a resolution on the direct dependencies.
> hot-fix: comments out pypi publishing

- conf/ephys_upload_job_configs.yml
- src/aind_data_transfer/__init__.py
- src/aind_data_transfer/configuration_loader.py
- src/aind_data_transfer/jobs/openephys_job.py
- tests/resources/test_configs/ephys_upload_job_test_configs.yml
- tests/resources/test_configs/example_configs_src_pattern1.yml
- tests/resources/test_configs/example_configs_src_pattern2.yml
- tests/resources/test_metadata/processing.json
- tests/test_configuration_loader.py
Closes #81
Things to do down the road:
- Store the openehpys job configs as a pydantic model and serialize it to json and send as a parameter to the code ocean trigger capsule. Deserialize back into the pydantic in the code ocean trigger capsule.
> Feat 81 codeocean capsule

- src/aind_data_transfer/__init__.py
- src/aind_data_transfer/config_loader/configuration_loader.py
- src/aind_data_transfer/config_loader/ephys_configuration_loader.py
- src/aind_data_transfer/jobs/openephys_job.py
- src/aind_data_transfer/jobs/transcode_job.py
- tests/test_configuration_loader.py
- tests/test_metadata_creation.py
Closes #95 
- We may want to keep the imaging and ephys classes in separate modules so we can do `pip install aind-data-transfer[ephys]` and `pip install aind-data-transfer[imaging]`
> fix: refactors config loaders

- conf/ephys_upload_job_configs.yml
- src/aind_data_transfer/__init__.py
- src/aind_data_transfer/jobs/openephys_job.py
- src/aind_data_transfer/writers.py
- tests/resources/test_configs/ephys_upload_job_test_configs.yml
- tests/resources/test_configs/example_configs_src_pattern1.yml
- tests/resources/test_configs/example_configs_src_pattern2.yml
- tests/resources/test_metadata/processing.json
- tests/test_configuration_loader.py
Closes #97
Closes #87
- Makes MAX_WINDOWS_FILENAME_LENGTH configurable
- Leaves raw data pristine, and fixes settings.xml file in clipped folder only
- Fixes an issue with the video_encryption key in the test resources
> Refactor 97 add config

- src/aind_data_transfer/transcode/ome_zarr.py
- this parameter was removed from `xarray-multiscale` 1.1.0
> Fix: remove depth argument from multiscale

- src/aind_data_transfer/jobs/s3_upload_job.py
- src/aind_data_transfer/transformations/metadata_creation.py
- src/aind_data_transfer/util/s3_utils.py
- tests/test_generic_upload_job.py
- tests/test_metadata_creation.py
Closes #126 
- Adds a basic job to upload a folder to s3, also attaches subject metadata and data_description json files.
Can be run as follows:
Required arguments
```
python -m aind_data_transfer.jobs.s3_upload_job --data-source 'path_to_data_folder' --s3-bucket 's3_bucket' --subject-id '12345' --modality 'ecephys' --acq-date '2022-12-21' --acq-time '12-00-00' 
python -m aind_data_transfer.jobs.s3_upload_job -d 'path_to_data_folder' -b 's3_bucket' -s '12345' -m 'ecephys' -a '2022-12-21' -t '12-00-00'
```
Optional aws region (defaults to us-west-2)
```
python -m aind_data_transfer.jobs.s3_upload_job ... --s3-region 'us-east-1'
python -m aind_data_transfer.jobs.s3_upload_job ... -r 'us-east-1'
```
Optional service endpoints (defaults to retrieving from AWS Secrets Manager. None if not …
> Feat 126 generic job

- src/aind_data_transfer/jobs/s3_upload_job.py
- tests/test_generic_upload_job.py
Closes #133
Hot fix for an issue running the generic upload job on a windows machine. Apparently, python's NamedTemporaryFiles are not readable in windows. A workaround is to write a file in python's TemporaryDirectory directory. I tested this and it appears to work.
> fix: fixes issue with generic job on windows

- src/aind_data_transfer/config_loader/ephys_configuration_loader.py
- tests/resources/test_metadata/processing.json
- tests/test_ephys_config_loader.py
- tests/test_metadata_creation.py
Closes #151
- Makes it so a few endpoints (such as the trigger capsule id and metadata-service url) can be pulled from a central location (aws secrets manager). Originally, they were being defined in a conf file, but that means we'd have to update that file if any of the configs get updated.
> feat: update endpoint resolver

- README.md
- src/aind_data_transfer/jobs/s3_upload_job.py
- src/aind_data_transfer/transformations/ephys_compressors.py
- src/aind_data_transfer/transformations/video_compressors.py
- src/aind_data_transfer/util/s3_utils.py
- src/aind_data_transfer/writers/ephys_writers.py
- tests/test_compressors.py
- tests/test_generic_upload_job.py
Closes #155 
- Allows users of the generic s3 upload job to define a behavior directory so that it can be in a separate folder on upload.
> feat: optional behavior dir for s3_upload_job

- src/aind_data_transfer/transcode/ome_zarr.py
The latest `xarray-multiscale` release `1.1.1` makes it necessary to explicitly pass the `chunks` argument to the `multiscale` function, or it will use the default chunk size/shape of 128MB
> Fix: xarray-multiscale overwriting chunk size with default

- pyproject.toml
- attempting to write a zarr file to an s3 path will instead write to the current directory
- revert to `dask==2022.12.1` and `distributed==2022.12.1` and `zarr==2.13.3`, which fixes the issue
> Fix: zarr s3 write bug in dask[distributed]>=2023.1.0

- scripts/s3_upload.py
Fixes the following when running without a `pipeline_config` argument
```
Traceback (most recent call last):
File "/home/svc_aind_upload/cameron.arshadi/repos/aind-data-transfer/scripts/s3_upload.py", line 338, in <module>
main()
File "/home/svc_aind_upload/cameron.arshadi/repos/aind-data-transfer/scripts/s3_upload.py", line 253, in main
capsule_id = pipeline_config["co_capsule_id"]
TypeError: 'NoneType' object is not subscriptable
```
> Fix s3_upload.py

- src/aind_data_transfer/jobs/openephys_job.py
Some of the processing metadata json files look like the example below. This PR should fix things moving forward. Not sure if we want to fix the existing files in s3.
```
{
"describedBy": "https://raw.githubusercontent.com/AllenNeuralDynamics/aind-data-schema/main/src/aind_data_schema/processing.py",
"schema_version": "0.1.0",
"pipeline_version": null,
"pipeline_url": null,
"data_processes": [
{
"name": "ProcessName.EPHYS_PREPROCESSING",
"version": "0.9.2",
"start_date_time": "2023-03-14 23:45:20.487959+00:00",
"end_date_time": "2023-03-14 23:46:29.097181+00:00",
...
```
> hotfix: fixes openephys job enum bug

- pyproject.toml
- src/aind_data_transfer/transformations/ephys_compressors.py
- tests/test_compressors.py
fixes #188 
The LSB correction has been implemented in SpikeInterface>=0.97.1 
See implementation here: https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/preprocessing/correct_lsb.py
@jtyoung84 should I remove the `disable_tqdm` everywhere, since it's not used anymore?
> Feat 188: Use spikeinterface for LSB correction

- src/aind_data_transfer/jobs/s3_upload_job.py
If `behavior_path` is None, `Path(behavior_path)` raises a `TypeError`.
`behavior_path` is already the correct type for `upload_raw_data_folder()`.
> Fix a type bug in `jobs.s3_upload_job`

- src/aind_data_transfer/jobs/s3_upload_job.py
- tests/test_basic_job.py
- tests/test_generic_upload_job.py
Closes #217 
- Adds logic to skip a job in a jobs list if it has an error
- Old logic terminated all remaining jobs in the job list
- Logs an error message after all jobs are processed in case any had errors.
> feat: skips jobs with errors

- src/aind_data_transfer/transcode/ome_zarr.py
- ensures they are processed in the same order each time, which is useful if the job needs to be resumed post-failure
> Feat: sort image paths during zarr conversion

- scripts/write_ome_zarr.py
- With dask_mpi, it is necessary to do this or the job will continue in an idle state until it hits the specified walltime
> Fix: shutdown and close dask client

- src/aind_data_transfer/util/io_utils.py
- tests/test_io_utils.py
- tests/test_ome_zarr.py
Imaris adds 0-padding to the image to make each dimension divisible by 2 across all pyramid levels.
The true size of the image is stored in the `DataSetInfo/Image` group under attributes `X`, `Y`, and `Z`.
We can crop the dask and numpy arrays to this shape before returning them to the user.
> Feat: remove padding from Imaris-based arrays

- conf/transcode_job_configs.yml
- scripts/make_mips.py
- scripts/write_ome_zarr.py
- src/aind_data_transfer/jobs/transcode_job.py
- src/aind_data_transfer/transformations/flatfield_correction.py
- src/aind_data_transfer/transformations/ome_zarr.py
- tests/test_deinterleave.py
- tests/test_flatfield_correction.py
- tests/test_ome_zarr.py
This PR adds optional background subtraction to the transcode job. To use it, set `background_subtraction: true` in the `transcode_job_configs.yml` file. It will look for a file named like `bkg_tile_[XYZ coordinates].tiff`, e.g., `bkg_tile_x_0000_y_0001_z_0002.tiff`  in the `derivatives/` dir for each raw tile path. It will only work for non-interleaved files.
I also moved the `ome_zarr.py` module to `transformations` and removed the `transcode` package.
> Feat: optional background subtraction during zarr conversion

- src/aind_data_transfer/jobs/basic_job.py
- src/aind_data_transfer/util/s3_utils.py
- tests/test_basic_job.py
Closes #231 
- Adds subprocess check to bubble up errors from subprocess
- Adds check that aws is installed on users machine before doing any processing
- Adds check that user has write permissions to bucket before doing any processing
> feat: adds aws creds check

- src/aind_data_transfer/jobs/basic_job.py
- tests/test_basic_job.py
Closes #240 
- Removes mkdir command since it causes issues with the shutil.copytree command
- Adds additional logging to help troubleshoot problems
> fix: removes mkdir command

- README.md
- src/aind_data_transfer/config_loader/base_config.py
- src/aind_data_transfer/jobs/basic_job.py
- src/aind_data_transfer/jobs/s3_upload_job.py
- tests/test_base_config.py
- tests/test_basic_job.py
Closes #250 
- Adds option to skip copying uncompressed data to staging directory
- For example, 
```
python -m aind_data_transfer.jobs.s3_upload_job --jobs-csv-file "jobs_list.csv" --dry-run --skip-staging
```
or
```
python -m aind_data_transfer.jobs.s3_upload_job --jobs-csv-file "jobs_list.csv" --skip-staging
```
will upload the data directly to s3. This is currently ignored if the compress_data flag is true.
> feat: adds option to skip staging step

- src/aind_data_transfer/util/s3_utils.py
- Fixes a bug where the s3 upload command wasn't converting paths to strings.
- This explicitly stringifies the input directory when it's passed into the shell command
> fix: stringifies dirs in aws upload subprocess

- .github/workflows/ci.yml
- .github/workflows/tag_and_publish.yml
- conf/dask/dask-config.yaml
- pyproject.toml
- scripts/write_ome_zarr.py
- src/aind_data_transfer/transformations/ome_zarr.py
- src/aind_data_transfer/util/chunk_utils.py
- src/aind_data_transfer/util/io_utils.py
- tests/test_io_utils.py
- tests/test_ome_zarr.py
This PR implements a blocked writing strategy for OME-Zarr datasets. Dask arrays are partitioned into non-overlapping blocks of size ~400GiB and processed serially. Parallel processing is done within each block. This basically eliminates the scheduler overhead and OOM errors I was seeing when processing whole tiles / brain volumes at once, and doesn't slow down the writing. For downsampling (diSPIM), the previous level is re-read from either the output s3 bucket (levels 1-n) or disk (level 0), which significantly speeds up pyramid generation since previously the full-resolution layer was re-read for each downsampling level. 
Changes
* `BlockedArrayWriter` class which handles the array partitioning and writing. `ome-zarr-py` is only used for writing the OME-NGFF metadata now.
* Drops …
> Feat: improve scalability and performance of OME-Zarr writer

- pyproject.toml
Closes #184
- The pip install command downloaded many versions of botocore to resolve some dependency conflicts
- This pins s3transfer and botocore to mitigate that behavior
> enh: pins s3transfer to speed up dep resolver

- post_install.sh
- scripts/singularity/Dockerfile
- scripts/singularity/README.md
- scripts/singularity/aind_data_transfer.def
- scripts/singularity/build_sif.sh
- scripts/singularity/run_build.sh
Closes #258 
- Adds no-cache-dir to post_install script to reduce size of singularity images
- Adds Dockerfile to build an environment with Singularity installed
- Adds def file to pip install aind-data-transfer[full] and run post_install script
- Add README explaining how to build a singularity image that can be run on the HPC as an alternative to conda envs.
> ci: adds instructions on how to build singularity image

- pyproject.toml
- scripts/convert_n5_zarr.py
- src/aind_data_transfer/transformations/ome_zarr.py
The script takes a BigDataViewer-style multiscale N5 (on disk or cloud) and converts it to OME-Zarr. If there are fewer scales in the N5 than desired, the pyramid is generated from scratch. 
**Benchmarks**
In this case all scales exist in the N5, so no downsampling was done.
Source N5 (multiscale, GZip compressed): `s3://aind-open-data/exaSPIM_650010_2023-04-04_17-42-51_fusion_2023-04-23_11-35-00/fused.n5`
Dest Zarr (multiscale, Blosc Zstd compressed): another S3 bucket
Machine: Allen HPC
N Cores: `64`
Raw data size (all pyramid levels): `89187 GiB`
Conversion time: `65563s`
Speed: `1.36GiB/s`
N5 chunk size: `(256, 256, 256)`
Zarr chunk size: `(256, 256, 256)`
> Feat: script for converting N5 datasets to OME-Zarr

- README.md
closes #269 
updated readme to reflect that:
- SPOPHYS experiment_type field should be `single-pane-ophys` 
- imply that the experiment_type field should be filled with the value of Modality.abbreviation
> fix SPOPHYS experiment type readme

- src/aind_data_transfer/jobs/transcode_job.py
- transcode must be finished before creating neuroglancer link or reading the output zarr will fail.
> fix neuroglancer link creation in transcode_job.py

- src/aind_data_transfer/transformations/flatfield_correction.py
- src/aind_data_transfer/transformations/ome_zarr.py
- tests/test_flatfield_correction.py
* Fix integer overflow for pixels near uint16 max value
* cast input array to int32 to avoid potential underflow
* load background dask array as part of computation instead of on client machine
* fix dimension adjustments when array sizes are not equal
> Fix background subtraction

- scripts/gcs_upload.py
- scripts/make_mips.py
- scripts/s3_upload.py
- src/aind_data_transfer/gcs.py
- src/aind_data_transfer/s3.py
- src/aind_data_transfer/transformations/ome_zarr.py
- src/aind_data_transfer/util/file_utils.py
- tests/test_file_utils.py
This PR changes how file collection works for the `s3_upload.py` script. 
Currently, the entire input directory is scanned and upload-able file paths are added to a list. The whole list is then chunked and chunks are passed to dask workers for upload. This step can take hours when there are millions of small files. 
Instead, we can batch files for upload during the directory scan. Files are accumulated into batches with size `total_bytes <= target_bytes` and each batch is submitted as a separate upload task.
`os.scandir` is used to take advantage of the cached stat information, which is discarded with `os.walk`
There were a couple breaking changes:
* `aind_data_transfer.util.file_utils.collect_filepaths` now returns a `Generator` instead of `List`
* the `batch_num` parameter in …
> Feat: improve s3_upload.py performance

- src/aind_data_transfer/jobs/basic_job.py
Closes #289 
- Allows option to run a job using a single env var str to define the job config
- This will make it easier to submit multiple jobs to the slurm cluster using a single script command running in different envs
> feat: adds option to define job through env var

- src/aind_data_transfer/writers/ephys_writers.py
- tests/resources/test_metadata/processing.json
@jtyoung84 
The issue is that the new SpikeInterface version uses the `folder` kwarg (instead of the `zarr_path`).
Can you test if this fixes the output folder issue?
> Fix writing ephys to output folder with SI 0.100.0

- scripts/singularity/aind_data_transfer.def
- src/aind_data_transfer/transformations/ome_zarr.py
- tests/test_metadata_creation.py
Resolves the following error during S3 upload
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/s3fs/core.py", line 113, in _error_wrapper
return await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiobotocore/client.py", line 386, in _make_api_call
raise error_class(parsed_response, operation_name)
^^^^^^^^^^^^^^^^^
botocore.exceptions.ClientError: An error occurred (XAmzContentSHA256Mismatch) when calling the PutObject operation: The provided 'x-amz-content-sha256' header does not match what was computed.
```
- We first noticed this error on 2/27. `use_ssl=False` had not caused problems prior to then. Setting to `True` resolves the issue.
- Use py3.10 for singularity definition since there may be a bug in asyncio …
> Fix XAmzContentSHA256Mismatch on OME-Zarr upload

- pyproject.toml
- src/aind_data_transfer/writers/ephys_writers.py
- tests/test_ecephys_compression.py
@jtyoung84 turns out it was a spikeinterface bug (https://github.com/SpikeInterface/spikeinterface/pull/2639) that prevented the correct propagation of the compressor to zarr.
Made a patch release and updated the requirements
> Upgrade spikeinterface to fix wrong compressor

- src/aind_data_transfer/jobs/cronjobs/exaspim_cron_job.py
This is causing the zarr upload pipeline to fail at the moment
> Hotfix: adds project name to ExASPIM cron job

- pyproject.toml
- src/aind_data_transfer/transformations/ome_zarr.py
- tests/test_ome_zarr.py
Resolves #342 
Neuroglancer [link](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B7.480000148631623e-7%2C%22m%22%5D%2C%22y%22:%5B7.479999743009398e-7%2C%22m%22%5D%2C%22z%22:%5B0.000001%2C%22m%22%5D%2C%22t%22:%5B0.001%2C%22s%22%5D%7D%2C%22position%22:%5B-26688.111328125%2C-11572.4228515625%2C-10220.5%2C0%5D%2C%22crossSectionScale%22:148.41315910257669%2C%22projectionScale%22:65536%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%5B%22zarr://s3://aind-open-data/exaSPIM_706434_2024-05-21_12-56-07/SPIM.ome.zarr/tile_x_0000_y_0000_z_0000_ch_488.zarr%22%2C%22zarr://s3://aind-open-data/exaSPIM_706434_2024-05-21_12-56-07/SPIM.ome.zarr/tile_x_0000_y_0001_z_0000_ch_488.zarr%22%2C%22zarr://s3://aind-open-data/exaSPIM_706434_2024-05-21_12-56-07/SPIM.ome.zarr/tile_ …
> Hotfix: incorrect OME-Zarr translation metadata
